#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Control — JOSS manuscript PDF metadata.
"""Replace renderer metadata with content-correct Info and XMP fields."""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from xml.sax.saxutils import escape
from zoneinfo import ZoneInfo

import pikepdf

_FONT_GENERATOR_COMMENT = b"% Generated by MetaType1 (a MetaPost-based engine)"


def _document_metadata(metadata_path: Path) -> tuple[str, str, str, str, datetime]:
    """Read the paper's declared metadata and its fixed revision-build time."""
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    title = metadata["title"]
    author = metadata["author"]["name"]
    subject = metadata["pdf_subject"]
    keywords = metadata["pdf_keywords"]
    epoch = metadata["source_date_epoch"]
    if not all(isinstance(value, str) and value.strip() for value in (title, author, subject, keywords)):
        raise ValueError("paper PDF metadata fields must be nonempty strings")
    if isinstance(epoch, bool) or not isinstance(epoch, int) or epoch <= 0:
        raise ValueError("source_date_epoch must be a positive integer")
    if len([word for word in keywords.split(";") if word.strip()]) < 4:
        raise ValueError("pdf_keywords must contain at least four semicolon-separated keywords")
    built_at = datetime.fromtimestamp(epoch, UTC).astimezone(ZoneInfo("Europe/Zurich"))
    return title, author, subject, keywords, built_at


def clean_pdf(source: Path, destination: Path, metadata_path: Path) -> None:
    """Save a deterministic review PDF with matching Info and XMP metadata."""
    title, author, subject, keywords, built_at = _document_metadata(metadata_path)
    offset = built_at.strftime("%z")
    pdf_date = built_at.strftime("D:%Y%m%d%H%M%S") + offset[:3] + "'" + offset[3:] + "'"
    iso_date = built_at.isoformat(timespec="seconds")
    xmp = (
        '<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
        '<rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/" '
        'xmlns:pdf="http://ns.adobe.com/pdf/1.3/" xmlns:xmp="http://ns.adobe.com/xap/1.0/">'
        f'<dc:title><rdf:Alt><rdf:li xml:lang="x-default">{escape(title)}</rdf:li></rdf:Alt></dc:title>'
        f"<dc:creator><rdf:Seq><rdf:li>{escape(author)}</rdf:li></rdf:Seq></dc:creator>"
        f'<dc:description><rdf:Alt><rdf:li xml:lang="x-default">{escape(subject)}</rdf:li></rdf:Alt></dc:description>'
        "<dc:language><rdf:Bag><rdf:li>en-GB</rdf:li></rdf:Bag></dc:language>"
        "<dc:format>application/pdf</dc:format>"
        f"<pdf:Keywords>{escape(keywords)}</pdf:Keywords>"
        f"<xmp:CreatorTool>{escape(author)}</xmp:CreatorTool>"
        f"<xmp:CreateDate>{iso_date}</xmp:CreateDate>"
        f"<xmp:ModifyDate>{iso_date}</xmp:ModifyDate>"
        f"<xmp:MetadataDate>{iso_date}</xmp:MetadataDate>"
        '</rdf:Description></rdf:RDF></x:xmpmeta>\n<?xpacket end="w"?>'
    )
    info = pikepdf.Dictionary(
        Title=pikepdf.String(title),
        Author=pikepdf.String(author),
        Subject=pikepdf.String(subject),
        Keywords=pikepdf.String(keywords),
        Creator=pikepdf.String(author),
        CreationDate=pikepdf.String(pdf_date),
        ModDate=pikepdf.String(pdf_date),
    )
    with pikepdf.open(source) as pdf:
        for obj in pdf.objects:
            if isinstance(obj, pikepdf.Stream):
                stream_data = obj.read_bytes()
                if _FONT_GENERATOR_COMMENT in stream_data:
                    # Keep Type1 font segment lengths unchanged.
                    replacement = b"%" + b" " * (len(_FONT_GENERATOR_COMMENT) - 1)
                    obj.write(stream_data.replace(_FONT_GENERATOR_COMMENT, replacement))
        pdf.Root.Metadata = pdf.make_stream(xmp.encode("utf-8"), Type=pikepdf.Name.Metadata, Subtype=pikepdf.Name.XML)
        pdf.Root.Lang = pikepdf.String("en-GB")
        pdf.trailer.Info = pdf.make_indirect(info)
        pdf.save(destination, deterministic_id=True)


def main() -> int:
    """Rewrite one rendered JOSS PDF using the package metadata file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--metadata", type=Path, default=Path(__file__).with_name("submission_metadata.json"))
    args = parser.parse_args()
    clean_pdf(args.source, args.destination, args.metadata)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
