# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Control — Generated traceability freshness check tests

"""Exercise actual valid registry/exact report freshness entry points and public references."""

from __future__ import annotations

import doctest
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from tools import check_generated_traceability as freshness_module
from tools.check_generated_traceability import (
    ROOT,
    expected_traceability_markdown,
    generated_traceability_is_current,
    main,
)
from validation.generate_physics_traceability_report import generate_physics_traceability_markdown


def test_generated_traceability_check_passes_for_repository_state(capsys: pytest.CaptureFixture[str]) -> None:
    """Run the default freshness CLI against actual canonical source/report bytes."""
    assert main([]) == 0
    output = capsys.readouterr().out
    normalized_output = output.replace("\\", "/")
    assert "Generated traceability documentation is current:" in output
    assert "validation/physics_traceability.json" in normalized_output
    assert "docs/physics_traceability.md" in normalized_output


def test_generated_traceability_check_detects_stale_report(tmp_path: Path) -> None:
    """Refuse an authored stale report against the real valid canonical registry."""
    stale_report = tmp_path / "physics_traceability.md"
    stale_report.write_text("stale report\n", encoding="utf-8")

    assert not generated_traceability_is_current(
        ROOT / "validation" / "physics_traceability.json",
        stale_report,
    )


def test_generated_traceability_cli_accepts_explicit_paths(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Exercise explicit actual canonical source/report CLI paths."""
    registry = ROOT / "validation" / "physics_traceability.json"
    report = ROOT / "docs" / "physics_traceability.md"

    assert main(["--registry", str(registry), "--report", str(report)]) == 0
    output = capsys.readouterr().out
    assert "Generated traceability documentation is current:" in output
    assert str(registry) in output
    assert str(report) in output


def test_generated_traceability_cli_reports_stale_explicit_path(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Return a stale diagnostic for actual mismatching report bytes."""
    registry = ROOT / "validation" / "physics_traceability.json"
    stale_report = tmp_path / "physics_traceability.md"
    stale_report.write_text("stale report\n", encoding="utf-8")

    assert main(["--registry", str(registry), "--report", str(stale_report)]) == 1
    assert f"{stale_report} is stale" in capsys.readouterr().err


def test_generated_traceability_cli_reports_missing_explicit_path(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Return a missing report diagnostic through the actual CLI."""
    registry = ROOT / "validation" / "physics_traceability.json"
    missing_report = tmp_path / "missing_physics_traceability.md"

    assert main(["--registry", str(registry), "--report", str(missing_report)]) == 1
    assert f"{missing_report} is missing" in capsys.readouterr().err


def test_generated_traceability_cli_reports_missing_registry_path(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Return a missing source diagnostic without generating a report."""
    missing_registry = tmp_path / "missing_physics_traceability.json"
    report = ROOT / "docs" / "physics_traceability.md"

    assert main(["--registry", str(missing_registry), "--report", str(report)]) == 1
    assert f"{missing_registry} is missing" in capsys.readouterr().err


def test_generated_traceability_check_detects_missing_tracker_line(
    tmp_path: Path,
) -> None:
    """Refuse real generated bytes with one actual tracker line removed."""
    registry = ROOT / "validation" / "physics_traceability.json"
    current_report = expected_traceability_markdown(registry)
    tracker_line = next(
        line for line in current_report.splitlines() if line.startswith("- External gyrokinetic validation artefacts:")
    )
    drifted_report = current_report.replace(f"{tracker_line}\n", "")
    report_path = tmp_path / "physics_traceability.md"
    report_path.write_text(drifted_report, encoding="utf-8")

    assert not generated_traceability_is_current(registry, report_path)


def test_validation_docs_include_generated_traceability_check_entrypoint() -> None:
    """Keep the public generator/freshness instructions wired to their real entry points."""
    validation_docs = (ROOT / "docs" / "validation.md").read_text(encoding="utf-8")

    assert (
        "python validation/generate_physics_traceability_report.py --output-md docs/physics_traceability.md"
        in validation_docs
    )
    assert "python tools/check_generated_traceability.py" in validation_docs


def test_identical_failed_diagnostic_cannot_pass_freshness(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Refuse byte-identical output from an actual invalid registry across API and CLI."""
    payload = json.loads((ROOT / "validation/physics_traceability.json").read_text())
    payload["entries"][0].update(unit_contract="", public_claim_allowed=True)
    registry = tmp_path / "registry.json"
    registry.write_text(json.dumps(payload))
    report = tmp_path / "report.md"
    report.write_text(generate_physics_traceability_markdown(registry))
    with pytest.raises(ValueError, match="registry failed validation"):
        expected_traceability_markdown(registry)
    assert not generated_traceability_is_current(registry, report)
    assert main(["--registry", str(registry), "--report", str(report)]) == 1
    assert "cannot be validated" in capsys.readouterr().err


@pytest.mark.parametrize("kind", ["invalid_utf8", "directory", "missing"])
def test_actual_freshness_report_read_refusals(tmp_path: Path, kind: str) -> None:
    """Treat real unreadable/undecodable output as false through the public boolean API."""
    report = tmp_path / "report.md"
    if kind == "invalid_utf8":
        report.write_bytes(b"\xff")
    elif kind == "directory":
        report.mkdir()
    assert not generated_traceability_is_current(ROOT / "validation/physics_traceability.json", report)


@pytest.mark.parametrize("no_site", [False, True])
def test_actual_freshness_standard_library_cli_bootstrap_without_site(tmp_path: Path, no_site: bool) -> None:
    """Exercise actual standalone import bootstrap and missing-path diagnostic with/without site."""
    c = subprocess.run(
        [
            sys.executable,
            *(["-S"] if no_site else []),
            str(ROOT / "tools/check_generated_traceability.py"),
            "--registry",
            str(tmp_path / "missing.json"),
        ],
        cwd=tmp_path,
        env=dict(os.environ, PYTHONPATH="", PYTHONDONTWRITEBYTECODE="1"),
        text=True,
        capture_output=True,
        check=False,
    )
    assert c.returncode == 1 and "is missing" in c.stderr and c.stdout == ""


def test_freshness_native_examples_execute() -> None:
    """Execute actual missing-input native boolean refusal with no private helper call."""
    result = doctest.testmod(freshness_module, raise_on_error=True)
    assert result.failed == 0 and result.attempted >= 2
