# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Control — Artifact compact packed-weight codec

"""Compact ``u64-le-zlib-base64`` packed-weight codec for controller artifacts.

This leaf owns deterministic encode/decode of uint64 packed weight payloads used
by ``.scpnctl.json`` compact form. Load/save, JSON schema, and payload hashing
remain on :mod:`scpn_control.scpn.artifact` (CTL-G07 R4-S3).
"""

from __future__ import annotations

import base64
import binascii
import zlib
from typing import Any

from scpn_control.scpn.artifact_model import (
    MAX_COMPRESSED_BYTES as _MODEL_MAX_COMPRESSED_BYTES,
)
from scpn_control.scpn.artifact_model import (
    MAX_DECOMPRESSED_BYTES as _MODEL_MAX_DECOMPRESSED_BYTES,
)
from scpn_control.scpn.artifact_model import (
    MAX_PACKED_WORDS as _MODEL_MAX_PACKED_WORDS,
)
from scpn_control.scpn.artifact_validate import ArtifactValidationError

# Module-level limits (defaults from the model leaf; tests may monkeypatch).
MAX_COMPRESSED_BYTES = _MODEL_MAX_COMPRESSED_BYTES
MAX_DECOMPRESSED_BYTES = _MODEL_MAX_DECOMPRESSED_BYTES
MAX_PACKED_WORDS = _MODEL_MAX_PACKED_WORDS


def _encode_u64_compact(data_u64: list[int]) -> dict[str, Any]:
    """Encode uint64 list as zlib-compressed base64 little-endian payload."""
    raw = bytearray()
    for value in data_u64:
        raw.extend(int(value & 0xFFFFFFFFFFFFFFFF).to_bytes(8, "little", signed=False))
    compressed = zlib.compress(bytes(raw), level=9)
    payload = base64.b64encode(compressed).decode("ascii")
    return {
        "encoding": "u64-le-zlib-base64",
        "count": len(data_u64),
        "data_u64_b64_zlib": payload,
    }


def _decode_u64_compact(encoded: dict[str, Any]) -> list[int]:
    """Decode compact uint64 payload generated by ``_encode_u64_compact``."""
    if encoded.get("encoding") != "u64-le-zlib-base64":
        raise ArtifactValidationError(f"Unsupported packed encoding: {encoded.get('encoding')}")

    payload = encoded.get("data_u64_b64_zlib")
    if not isinstance(payload, str):
        raise ArtifactValidationError("Missing compact packed payload string.")

    count_val = encoded.get("count")
    if isinstance(count_val, int) and (count_val < 0 or count_val > MAX_PACKED_WORDS):
        raise ArtifactValidationError(f"Packed count {count_val} exceeds limit {MAX_PACKED_WORDS}.")

    try:
        comp = base64.b64decode(payload.encode("ascii"), validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ArtifactValidationError(f"Invalid base64 payload: {exc}") from exc

    if len(comp) > MAX_COMPRESSED_BYTES:
        raise ArtifactValidationError(f"Compressed payload too large: {len(comp)} bytes.")

    try:
        decomp = zlib.decompressobj()
        raw = decomp.decompress(comp, MAX_DECOMPRESSED_BYTES + 1)
        if decomp.unconsumed_tail:
            raise ArtifactValidationError("Decompressed packed payload exceeds configured limit.")
        raw += decomp.flush()
    except ArtifactValidationError:
        raise
    except (zlib.error, ValueError, OSError) as exc:
        raise ArtifactValidationError(f"Invalid compact packed payload: {exc}") from exc

    if len(raw) > MAX_DECOMPRESSED_BYTES:
        raise ArtifactValidationError("Decompressed packed payload exceeds configured limit.")

    if len(raw) % 8 != 0:
        raise ArtifactValidationError(f"Compact packed payload byte-length {len(raw)} is not divisible by 8.")

    available = len(raw) // 8
    if isinstance(count_val, int):
        count = count_val
    elif count_val is None:
        count = available
    else:
        raise ArtifactValidationError(f"Invalid compact packed count type: {type(count_val).__name__}.")
    if count < 0 or count > available:
        raise ArtifactValidationError(f"Invalid compact packed count {count}; available words={available}.")

    return [int.from_bytes(raw[i * 8 : (i + 1) * 8], "little", signed=False) for i in range(count)]


def encode_u64_compact(data_u64: list[int]) -> dict[str, Any]:
    """Public compact codec helper for deterministic uint64 payload encoding."""
    return _encode_u64_compact(list(map(int, data_u64)))


def decode_u64_compact(encoded: dict[str, Any]) -> list[int]:
    """Public compact codec helper for deterministic uint64 payload decoding."""
    return _decode_u64_compact(encoded)
