# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Control — Hardware-in-the-Loop Test Harness

"""HIL FPGA SNN register-map export."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class SNNNeuronConfig:
    """LIF neuron configuration for FPGA register map."""

    neuron_id: int
    v_threshold: float = 0.35
    v_reset: float = 0.0
    tau_mem_us: float = 15000.0  # 15 ms
    i_bias: float = 0.1
    weight: float = 1.0


@dataclass
class FPGARegisterMap:
    """FPGA register map for SNN controller deployment."""

    clock_hz: int
    n_neurons: int
    dt_us: float
    neurons: list[SNNNeuronConfig]
    input_ports: list[str]
    output_ports: list[str]
    reset_active_low: bool = True


class FPGASNNExport:
    """Export SNN controller configuration as FPGA register map.

    Generates a deterministic register-level description suitable for
    synthesis via Vivado HLS or manual RTL implementation.

    Parameters
    ----------
    n_neurons : int
        Number of LIF neurons per channel.
    n_channels : int
        Number of push-pull control channels (e.g. R and Z).
    clock_mhz : float
        FPGA clock frequency (MHz).
    """

    def __init__(
        self,
        n_neurons: int = 50,
        n_channels: int = 2,
        clock_mhz: float = 100.0,
    ) -> None:
        self.n_neurons = int(n_neurons)
        self.n_channels = int(n_channels)
        self.clock_hz = int(clock_mhz * 1e6)

    def generate_register_map(
        self,
        v_threshold: float = 0.35,
        tau_mem_us: float = 15000.0,
        dt_us: float = 1000.0,
    ) -> FPGARegisterMap:
        """Generate the full register map for all neurons."""
        neurons: list[SNNNeuronConfig] = []
        for ch in range(self.n_channels):
            for nid in range(self.n_neurons):
                neurons.append(
                    SNNNeuronConfig(
                        neuron_id=ch * self.n_neurons + nid,
                        v_threshold=v_threshold,
                        tau_mem_us=tau_mem_us,
                    )
                )

        input_ports = [f"error_ch{ch}" for ch in range(self.n_channels)]
        output_ports = [f"spike_rate_ch{ch}" for ch in range(self.n_channels)]

        return FPGARegisterMap(
            clock_hz=self.clock_hz,
            n_neurons=self.n_neurons * self.n_channels,
            dt_us=dt_us,
            neurons=neurons,
            input_ports=input_ports,
            output_ports=output_ports,
        )

    def export_verilog_header(self, reg_map: FPGARegisterMap) -> str:
        """Generate Verilog module header for the SNN controller.

        This is a register-level description, not a full synthesizable design.
        It defines the I/O ports and parameter registers for HLS integration.
        """
        lines = [
            "// Auto-generated by SCPN Control — FPGASNNExport",
            f"// {reg_map.n_neurons} LIF neurons, {self.n_channels} channels",
            f"// Clock: {reg_map.clock_hz / 1e6:.0f} MHz, dt: {reg_map.dt_us:.0f} us",
            "",
            "module snn_controller #(",
            f"    parameter N_NEURONS = {reg_map.n_neurons},",
            f"    parameter N_CHANNELS = {self.n_channels},",
            f"    parameter CLK_HZ = {reg_map.clock_hz},",
            f"    parameter DT_TICKS = {int(reg_map.dt_us * reg_map.clock_hz / 1e6)}",
            ") (",
            "    input  wire clk,",
            f"    input  wire {'rst_n' if reg_map.reset_active_low else 'rst'},",
        ]

        for port in reg_map.input_ports:
            lines.append(f"    input  wire signed [15:0] {port},")
        for i, port in enumerate(reg_map.output_ports):
            comma = "," if i < len(reg_map.output_ports) - 1 else ""
            lines.append(f"    output reg  signed [15:0] {port}{comma}")

        lines.append(");")
        lines.append("")

        # Parameter registers
        n = reg_map.neurons[0] if reg_map.neurons else SNNNeuronConfig(neuron_id=0)
        v_th_fixed = int(n.v_threshold * 2**14)
        tau_ticks = int(n.tau_mem_us * reg_map.clock_hz / 1e6)
        lines.append("    // Neuron parameters (Q2.14 fixed-point)")
        lines.append(f"    localparam V_THRESHOLD = 16'sd{v_th_fixed};")
        lines.append(f"    localparam TAU_TICKS   = 32'd{tau_ticks};")
        lines.append("")
        lines.append("    // Membrane potential register file")
        lines.append("    reg signed [15:0] v_mem [0:N_NEURONS-1];")
        lines.append("")
        lines.append("    // Full LIF design: see sc-neurocore/hdl/lif_neuron.v")
        lines.append("    // Integrate via Vivado HLS or instantiate RTL directly")
        lines.append("")
        lines.append("endmodule")

        return "\n".join(lines)


# ─── HIL Benchmark ───────────────────────────────────────────────────
