#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Control — Generated traceability freshness check
"""Check valid registry input and exact generated Markdown bytes.

This local freshness gate checks no timestamp, source hash, facility evidence,
remote issue state or scientific promotion. Invalid source or unreadable output
cannot pass merely because a diagnostic report matches its generated bytes.

Examples
--------
>>> from tempfile import TemporaryDirectory
>>> with TemporaryDirectory() as directory:
...     current = generated_traceability_is_current(Path(directory) / "missing.json", Path(directory) / "missing.md")
>>> current
False
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from validation.generate_physics_traceability_report import generate_physics_traceability_markdown


def expected_traceability_markdown(registry: Path) -> str:
    """Generate deterministic Markdown only from a passing local registry.

    Return a newline-terminated string. The underlying strict generator raises
    ValueError on failed source validation; metadata PASS is not scientific proof.
    """
    return generate_physics_traceability_markdown(registry, require_valid_registry=True)


def generated_traceability_is_current(registry: Path, report_path: Path) -> bool:
    """Require valid source and exact generated UTF-8 bytes, returning a boolean.

    Invalid registry, supported generator/path/read/decode failure, missing or
    mismatching report returns false. No write, publication or freshness clock check.
    """
    try:
        expected = expected_traceability_markdown(registry).encode("utf-8")
        actual = report_path.read_bytes()
    except (OSError, ValueError):
        return False
    return actual == expected


def main(argv: list[str] | None = None) -> int:
    """Run the standalone exact-byte freshness check with canonical defaults.

    argv has argparse semantics. Missing paths print their missing diagnostic;
    stale/invalid/unreadable inputs print refusal instructions. Return0 on valid
    exact output or1 on refusal. No generation/write or remote check occurs.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--registry",
        default=str(ROOT / "validation" / "physics_traceability.json"),
        help="Physics traceability registry JSON path",
    )
    parser.add_argument(
        "--report",
        default=str(ROOT / "docs" / "physics_traceability.md"),
        help="Generated physics traceability Markdown path",
    )
    args = parser.parse_args(argv)

    registry = Path(args.registry)
    report_path = Path(args.report)
    if not registry.exists():
        print(f"{registry} is missing", file=sys.stderr)
        return 1
    if not report_path.exists():
        print(f"{report_path} is missing", file=sys.stderr)
        return 1
    if not generated_traceability_is_current(registry, report_path):
        print(
            f"{report_path} is stale or its registry/report cannot be validated; run python validation/generate_physics_traceability_report.py",
            file=sys.stderr,
        )
        return 1
    print(f"Generated traceability documentation is current: {registry} -> {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
