# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Control — Generate the native C ABI and Lean declaration reference.

"""Generate a checked reference from C header and Lean declaration comments."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "src/scpn_control/core/solver.h"
LEAN = ROOT / "lean/SCPNControl/PulsedFSM.lean"
OUTPUT = ROOT / "docs/_generated/native_api_reference.md"


def _clean_c_comment(raw: str) -> str:
    lines = [re.sub(r"^\s*\* ?", "", line).rstrip() for line in raw.splitlines()]
    return "\n".join(lines).strip()


def _normalise_signature(raw: str) -> str:
    return "\n".join(line.rstrip() for line in raw.strip().splitlines()) + ";"


def _c_declarations(source: str) -> list[tuple[str | None, str]]:
    declaration = re.compile(r"^SCPN_SOLVER_API\s+(.+?);", re.DOTALL | re.MULTILINE)
    documented = re.compile(r"/\*\*(.*?)\*/\s*^SCPN_SOLVER_API\s+(.+?);", re.DOTALL | re.MULTILINE)
    comments = {match.group(2).strip(): _clean_c_comment(match.group(1)) for match in documented.finditer(source)}
    return [
        (comments.get(match.group(1).strip()), _normalise_signature(match.group(1)))
        for match in declaration.finditer(source)
    ]


def _symbol_name(signature: str) -> str:
    match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*\(", signature)
    if match is None:
        raise ValueError(f"unable to identify C declaration: {signature}")
    return match.group(1)


def _lean_declarations(source: str) -> list[tuple[str, str, str]]:
    pattern = re.compile(
        r"/--\s*(.*?)\s*-/\s*(inductive|def|theorem)\s+([A-Za-z_][A-Za-z0-9_]*)",
        re.DOTALL,
    )
    return [(match.group(2), match.group(3), " ".join(match.group(1).split())) for match in pattern.finditer(source)]


def render() -> str:
    """Return the complete deterministic Markdown reference."""
    c_declarations = _c_declarations(HEADER.read_text(encoding="utf-8"))
    lean_declarations = _lean_declarations(LEAN.read_text(encoding="utf-8"))
    versioned = [(comment, sig) for comment, sig in c_declarations if _symbol_name(sig).startswith("scpn_solver_")]
    legacy = [(comment, sig) for comment, sig in c_declarations if not _symbol_name(sig).startswith("scpn_solver_")]

    if len(versioned) != 5 or len(legacy) != 5:
        raise ValueError(
            f"expected five versioned and five legacy C functions, found {len(versioned)} and {len(legacy)}"
        )
    if any(comment is None for comment, _ in versioned):
        raise ValueError("every versioned C function requires a Doxygen contract")
    if len(lean_declarations) != 9:
        raise ValueError(f"expected nine documented Lean declarations, found {len(lean_declarations)}")

    lines = [
        "# Native API and checked proof reference",
        "",
        "<!-- Generated by tools/generate_native_api_reference.py; do not edit. -->",
        "",
        "This reference is generated from `src/scpn_control/core/solver.h` and",
        "`lean/SCPNControl/PulsedFSM.lean`. The C header is the normative ABI",
        "contract. The Lean section describes only the checked finite-state model;",
        "it is not evidence of continuous plant or plasma safety.",
        "",
        "## C ABI version 1",
        "",
        "ABI version: `SCPN_SOLVER_ABI_VERSION == 1`. Status `OK` means the call",
        "was valid; convergence is reported separately by the convergence function.",
        "",
    ]
    for comment, signature in versioned:
        lines.extend([f"### `{_symbol_name(signature)}`", "", str(comment), "", "```c", signature, "```", ""])

    lines.extend(
        [
            "## Legacy compatibility ABI",
            "",
            "These unversioned symbols remain loadable for existing clients. They",
            "preserve historical null, zero, or silent error signalling. New clients",
            "should use the typed version 1 ABI above.",
            "",
        ]
    )
    for _, signature in legacy:
        lines.extend([f"### `{_symbol_name(signature)}`", "", "```c", signature, "```", ""])

    lines.extend(["## Lean checked declarations", ""])
    for kind, name, comment in lean_declarations:
        lines.extend([f"### `{name}`", "", f"Kind: `{kind}`. {comment}", ""])
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the reference, or fail if ``--check`` detects stale output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of updating stale output")
    args = parser.parse_args(argv)
    rendered = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated native API reference: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("native API reference is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
